### ISSUE TITLE
Erroring out upon encounter of malformed local folder for browser

### ISSUE THREAD

**Issue by XavierNCline** [Spec-ify/specify#18]
[OperaGXError.txt](https://github.com/Spec-ify/specify/files/10410782/OperaGXError.txt)
This error pertains to OperaGX specifically, but there is no reason this could not occur elsewhere. When the logic checks to see if the browser exists, it appears to implicitly act as though the Extensions folder exists. Better error handling needs to be implemented to prevent hard crashes here

**Comment by zleyyij** [comment]
This should be fixed
