### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by sealsrock12** [Spec-ify/specify#19]
Current work in gui-client branch

- [ ] Status text
- [x] Error handling

**Comment by zleyyij** [comment]
The GUI is currently almost ready to be merged into main thanks to @K97i. 
All that needs to be done is cleanup, with fixing the status text something to be looked at down the line.

**Comment by K97i** [comment]
For the sake of my sanity (I spent literal weeks on this), the status text would have to be either heavily delayed, or scrapped all together.

Databinding, Element Search, and just straight up targeting the element itself, doesn't update the UI to reflect the current status.

I don't know what is going wrong, might be WPF, Threading, or it might just be Windows being Windows.

**Comment by K97i** [comment]
Status text will be split into a separate issue for further discussion. GUI is now merged to the main branch as of [85a006f](https://github.com/Spec-ify/specify/commit/85a006f6c930f42a11596e91ab25954035bab12a).
