### ISSUE TITLE
tamper protection of results 

### ISSUE THREAD

**Issue by sealsrock12** [Spec-ify/specify#2]
[7:34 PM] Dreibaby: Specify generates an ID with every report and specified can generate the ID based on arbitrary information inside the report and compare

**Comment by XavierNCline** [comment]
After discussing this with Drei we came to the conclusion this is ultimately unnecessary. The default path for uploading data doesn't even allow for users to tamper with the data. Even if they used the manual upload method, a flag on this could cause other issues with whomever is reading the data.

Closing this as a reconsidered design choice.
