### ISSUE TITLE
Automatic Minidump Zipping

### ISSUE THREAD

**Issue by Drybaby** [Spec-ify/specify#21]
Create logic to handle minidump files when found.

Flow:
Minidumps Found
If Minidumps younger than a month:
Ask user if they want to upload them
Move minidump files away from the windows folder, zip them up, upload them to x0.at
Attach URL to json

**Comment by XavierNCline** [comment]
I'm going to implement all the logic needed to gather the dumps and upload them to that service. Prompting will have to wait until the GUI branch is merged into main. I asked @K97i in the Discord thread about confirmation dialogs appearing during data collection, it's not implemented yet in the GUI.

**Comment by XavierNCline** [comment]
Added in commit 58bf27f 

Closing issue
