### ISSUE TITLE
Win 10 requirements

### ISSUE THREAD

**Issue by JohnRo79** [Spec-ify/specify#48]
hi there

i have a windows 10 running and your handy app it just don't wanna start on it
This app can't run on your PC

what are the requirements for it to work pls?

**Comment by sealsrock12** [comment]
It needs a 64-bit computer and Windows 1809 or higher. Your error is probably because your computer is 32-bit.

**Comment by XavierNCline** [comment]
Closed this issue due to this more than likely being an incompatibility with an EOL version of Windows or a 32-bit version of Windows which this program is not designed to run with.
